[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.22"
evm_version = "paris"

remappings = [
    "@openzeppelin-5.0/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "solady/=lib/solady/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
